In [ ]:
# IMPORTING THE LIBRARIES

import numpy
import matplotlib.pyplot as plt
import statistics
from sklearn.model_selection import train_test_split
from scipy.stats import skew
from scipy.stats import kurtosis

In [ ]:
# MOUNTING THE FILE IN THE GOOGLE DRIVE

from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [ ]:
# LOADING THE FILE 
f = open('/content/gdrive/MyDrive/data/data.txt','r')




In [ ]:
# CONVERTING THE TEXT FILE TO A LIST

from numpy import loadtxt
a = loadtxt("/content/gdrive/MyDrive/data/data.txt", comments="#", delimiter=",", unpack=False)
F = a.tolist()

In [ ]:
# IMPORTING THE PANDAS FRAMEWORK

import pandas as pd

F_new = pd.read_csv("/content/gdrive/MyDrive/data/data.txt",
                             sep="\t")

In [ ]:
# CONVERTING THE LIST INTO A DATAFRAME

from pandas import DataFrame

fd = DataFrame(F)
print(fd)

            0        1        2        3   ...       11       12       13   14
0      4329.23  4009.23  4289.23  4148.21  ...  4280.51  4635.90  4393.85  0.0
1      4324.62  4004.62  4293.85  4148.72  ...  4279.49  4632.82  4384.10  0.0
2      4327.69  4006.67  4295.38  4156.41  ...  4282.05  4628.72  4389.23  0.0
3      4328.72  4011.79  4296.41  4155.90  ...  4287.69  4632.31  4396.41  0.0
4      4326.15  4011.79  4292.31  4151.28  ...  4288.21  4632.82  4398.46  0.0
...        ...      ...      ...      ...  ...      ...      ...      ...  ...
14975  4281.03  3990.26  4245.64  4116.92  ...  4269.23  4593.33  4340.51  1.0
14976  4276.92  3991.79  4245.13  4110.77  ...  4259.49  4590.26  4333.33  1.0
14977  4277.44  3990.77  4246.67  4113.85  ...  4257.95  4591.79  4339.49  1.0
14978  4284.62  3991.79  4251.28  4122.05  ...  4267.18  4596.41  4350.77  1.0
14979  4287.69  3997.44  4260.00  4121.03  ...  4274.36  4597.95  4350.77  1.0

[14980 rows x 15 columns]


In [ ]:
# MEAN

f_m = fd.mean(axis=1)
print(f_m)

0        4028.820667
1        4025.232000
2        4024.683333
3        4028.478667
4        4028.444000
            ...     
14975    4005.502667
14976    4001.741333
14977    4002.049333
14978    4007.382667
14979    4011.588667
Length: 14980, dtype: float64


In [ ]:
# MIN

f_min = fd.min(axis=1)
print(f_min)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
14975    1.0
14976    1.0
14977    1.0
14978    1.0
14979    1.0
Length: 14980, dtype: float64


In [ ]:
# MAX

f_max = fd.max(axis=1)
print(f_max)

0        4641.03
1        4638.97
2        4630.26
3        4632.31
4        4632.82
          ...   
14975    4625.64
14976    4621.54
14977    4623.59
14978    4628.72
14979    4638.46
Length: 14980, dtype: float64


In [ ]:
# STANDARD DEVIATION

f_std = fd.std(axis=1)
print(f_std)


0        1130.018529
1        1129.105818
2        1128.596095
3        1129.469530
4        1129.556390
            ...     
14975    1124.108676
14976    1123.150855
14977    1123.362685
14978    1124.715585
14979    1125.738216
Length: 14980, dtype: float64


In [ ]:
# SKEWNESS

f_skew = skew(fd, axis=1) 
print(f_skew)

[-3.31001064 -3.30894177 -3.31271713 ... -3.29749721 -3.29912401
 -3.30074746]


In [ ]:
# KURTOSIS

f_kurt = kurtosis(fd, axis=1)
print(f_kurt)

[9.38513633 9.38123938 9.39634339 ... 9.3373056  9.34334647 9.35013285]


In [ ]:
# ASSIGNING THE DATA TO TWO DIFFERENT VARIABLES

df = pd.DataFrame()

df['mean'] = f_m
df['min'] = f_min
df['max'] = f_max
df['stddev'] = f_std
df['skewness'] = f_skew
df['kurtosis'] = f_kurt

print(df)


              mean  min      max       stddev  skewness  kurtosis
0      4028.820667  0.0  4641.03  1130.018529 -3.310011  9.385136
1      4025.232000  0.0  4638.97  1129.105818 -3.308942  9.381239
2      4024.683333  0.0  4630.26  1128.596095 -3.312717  9.396343
3      4028.478667  0.0  4632.31  1129.469530 -3.314794  9.404399
4      4028.444000  0.0  4632.82  1129.556390 -3.313826  9.400218
...            ...  ...      ...          ...       ...       ...
14975  4005.502667  1.0  4625.64  1124.108676 -3.299973  9.346715
14976  4001.741333  1.0  4621.54  1123.150855 -3.298798  9.342677
14977  4002.049333  1.0  4623.59  1123.362685 -3.297497  9.337306
14978  4007.382667  1.0  4628.72  1124.715585 -3.299124  9.343346
14979  4011.588667  1.0  4638.46  1125.738216 -3.300747  9.350133

[14980 rows x 6 columns]


In [ ]:
# ALLOCATING THE VARIABLES TO X AND y variables

df.head()

mean  min      max       stddev  skewness  kurtosis
0  4028.820667  0.0  4641.03  1130.018529 -3.310011  9.385136
1  4025.232000  0.0  4638.97  1129.105818 -3.308942  9.381239
2  4024.683333  0.0  4630.26  1128.596095 -3.312717  9.396343
3  4028.478667  0.0  4632.31  1129.469530 -3.314794  9.404399
4  4028.444000  0.0  4632.82  1129.556390 -3.313826  9.400218

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Features
feature_cols = ['mean', 'min', 'max', 'stddev', 'skewness', 'kurtosis']

In [ ]:
target = df['min']
df1 = df.copy()
df1 = df1.drop('min', axis =1)

In [ ]:
X = df1
y = target


In [ ]:
# SPLITTING THE DATASET INTO TWO PARTS: TRAINING DATASET AND TESTING DATASET

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 10)

In [ ]:
from sklearn import preprocessing

In [ ]:
# PERFORM THE FEATURE SCALING

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)


In [ ]:
lab_enc = preprocessing.LabelEncoder()
y_train = lab_enc.fit_transform(y_train)
y_test = lab_enc.fit_transform(y_test)

In [ ]:
# FIT THE MODEL

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier = classifier.fit(X_train, y_train)


In [ ]:
# PREDICTION AND ACCURACY

y_pred = classifier.predict(X_test)


In [ ]:
# ACCURACY
from sklearn import metrics 

print('Accuracy Score:', metrics.accuracy_score(y_test,y_pred) * 100)

Accuracy Score: 70.0


In [ ]:
from sklearn.metrics import confusion_matrix ,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test,y_pred))

[[6 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.75      0.86      0.80         7
           1       0.50      0.33      0.40         3

    accuracy                           0.70        10
   macro avg       0.62      0.60      0.60        10
weighted avg       0.68      0.70      0.68        10



**SVM**

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.75      0.86      0.80         7
           1       0.50      0.33      0.40         3

    accuracy                           0.70        10
   macro avg       0.62      0.60      0.60        10
weighted avg       0.68      0.70      0.68        10



**RANDOM_FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=123456)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=123456,
                       verbose=0, warm_start=False)

In [ ]:
from sklearn.metrics import accuracy_score
predicted = rf.predict(X_test)
accuracy = accuracy_score(y_test, predicted)
print(accuracy)

0.7


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[6 1]
 [2 1]]
              precision    recall  f1-score   support

           0       0.75      0.86      0.80         7
           1       0.50      0.33      0.40         3

    accuracy                           0.70        10
   macro avg       0.62      0.60      0.60        10
weighted avg       0.68      0.70      0.68        10



**Neural Network**

In [ ]:
from keras.models import Sequential 
from keras.layers import Dense
# load the dataset
dataset = fd

In [ ]:
# split into input (X) and output (y) variables
X = dataset[0:15]
y = dataset[8:23]



In [ ]:
Xnew=X.values.reshape((-1,1))
ynew=y.values.reshape((-1,1))

In [ ]:
print(Xnew.shape)
print(ynew.shape)

(225, 1)
(225, 1)


In [ ]:
# define the keras model
model = Sequential()

model.add(Dense(10, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# fit the keras model on the dataset
model.fit(X, y, epochs=10, batch_size=50)


Epoch 1/10


ValueError: ignored

In [ ]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

**CNN ARCHITECTURE**

In [ ]:
import tensorflow as tf
from keras import layers
from keras import models

In [ ]:

model = models.Sequential()
model.add(layers.Conv1D(32, 5, activation='relu', padding='same', input_shape=(F.shape)))
model.add(layers.MaxPooling1D((2)))
model.add(layers.Flatten()) 
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(1, activation='softmax'))
model.summary()


AttributeError: ignored

In [ ]:
# compile the model
 
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=60)